### ISSUE TITLE
Leftover shoot commands resulting in double shots.

### ISSUE THREAD

**Issue by Dorover** [crkellen/bands#40]
If you run out of bullets and try to shoot, you can't, but the next time your ammo gets refilled you automatically shoot once. Same happens when reloading; when you're out of ammo and start reloading, just spam click shoot until your reload is done and you'll shoot automatically and will have a 0 second cooldown for the next shot. Both of these result in being able to do a double shot.

**Comment by crkellen** [comment]
I had forgotten to check for ammo. This is fixed.
