### ISSUE TITLE
I want feedback on destruction of blocks

### ISSUE THREAD

**Issue by crkellen** [crkellen/bands#56]
**Please fill out this Issue template to the best of your ability!**

#### Type of Issue
- [ ] This Issue is a Bug
- [ ] This Issue is a Feature Request
- [x] This Issue is a Design Issue/Request

**Hint:** *Design Issues or Requests are changes to existing features, not new ones.*

### Description of the Issue:

Until I find a solution I am mostly happy with, I want to hear any ideas or comments on what you would like to see for damage being applied to blocks. It could be colors, or images, or whatever. Currently I have them a subdued grey with a tinge of red, moving closer to a greyish red as it takes more damage.
Just reply to this with any ideas. I'll close this when I find a suitable solution.

**Comment by Alex-Meyer** [comment]
Applying a cracking decal on top of the blocks would work, if you want to make block colors changeable, simply making the blocks darker would be a simple solution.

**Comment by crkellen** [comment]
The original idea was a progressively more cracked image, however as I am currently avoiding using images, that is not implemented.

Additionally, as you guessed, I do want to make the block colors interchangeable, with making them darker being the solution to showing damage as the easy route.

Thanks for the feedback!

**Comment by crkellen** [comment]
Going to close this, I think it's good, no one has complained.
