### ISSUE TITLE
The reload bar keeps on growing if you die while reloading.

### ISSUE THREAD

**Issue by Dorover** [crkellen/bands#96]
**Please fill out this Issue template to the best of your ability!**

#### Type of Issue
- [x] This Issue is a Bug
- [ ] This Issue is a Feature Request
- [x] This Issue is a Design Issue/Request

**Hint:** *Design Issues or Requests are changes to existing features, not new ones.*

### Description of the Issue:
The reload animation is a bar that fills up. But if you die while reloading, the bar doesn't stop, but instead it just keeps on growing until you respawn.

### Steps to reproduce the Issue (For Bugs):

You need 2+ people. Shoot until you run out of ammo, then as you reload, someone else kills you. Then pay attention to the reload bar under the cross hair.

- [x] I am using Google Chrome
- [ ] I am using Mozilla Firefox
- [ ] I am using *YOUR_BROWSER*

### Additional comments or information:
Couldn't find a situation where this would affect the gameplay as respawning fixes the problem, so it's just a brief visual issue.

**Comment by crkellen** [comment]
This should be fixed in imgs.
